resolver: nightly-2016-03-13
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: b50b0ec9791f9450f442b41546eb191c80475c1e
flags:
  svod:
    library-only: false
    dev: false
