resolver: nightly-2015-12-24
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 984b408df88e8e42a5eef3dffbf14a6223922373
flags:
  svod:
    library-only: false
    dev: false
