resolver: nightly-2016-03-13
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 0be16b040c8ec32474968fc016217fe0e7763042
flags:
  svod:
    library-only: false
    dev: false
