resolver: nightly-2016-03-13
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 9510091f4784510a2544254eec523196ae37cfaa
flags:
  svod:
    library-only: false
    dev: false
