resolver: nightly-2016-03-13
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: f811e2ad673cc6683ba24bf09bb36cd73652ff35
flags:
  svod:
    library-only: false
    dev: false
