resolver: lts-5.5
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 57d684f95112fefc26b13fb819e7719bd0ab1112
extra-deps:
- htaglib-1.0.2
- path-io-1.1.0
- plan-b-0.2.0
- zip-0.1.0
flags:
  svod:
    library-only: false
    dev: false
