resolver: nightly-2016-03-13
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: f10e4c0d16bb6896d1d12e59574785461370f3f4
flags:
  svod:
    library-only: false
    dev: false
