resolver: nightly-2015-12-24
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 1921c94119e2eff6e10a679e5439dfd1593a871b
flags:
  svod:
    library-only: false
    dev: false
