resolver: nightly-2016-04-05
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 6cde47ceb633d7f9a845a0f58aba70d0927d8ea8
flags:
  svod:
    library-only: false
    dev: false
