resolver: nightly-2016-03-13
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: d594047d33f6ca0ffc5b61e4a22944aa22078d72
flags:
  svod:
    library-only: false
    dev: false
