resolver: nightly-2016-03-13
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: cfc6195347703be7ca80a76019184cda4ee82024
flags:
  svod:
    library-only: false
    dev: false
