resolver: nightly-2015-12-02
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: b9c0885cbaca545b29b9ba203541d68fdd7bf8c7
flags:
  svod:
    library-only: false
    dev: false
