resolver: lts-5.5
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: e00c8065ee69af6e1b0b57e99255f67e68f77f8c
extra-deps:
- htaglib-1.0.2
- path-io-1.1.0
- plan-b-0.2.0
- zip-0.1.0
flags:
  svod:
    library-only: false
    dev: false
