resolver: nightly-2015-12-02
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: f19dfcbfe052a7fcf8075931fe4b7cf107f2c399
flags:
  svod:
    library-only: false
    dev: false
