resolver: nightly-2015-12-02
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: ba1b00cabdae959955b4a4bda10aedda9cfe5b41
flags:
  svod:
    library-only: false
    dev: false
