resolver: lts-5.5
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 1a65b47cb53d0ccfcd0aedda693e10e91dc5fc73
extra-deps:
- htaglib-1.0.2
- path-io-1.1.0
- plan-b-0.2.0
- zip-0.1.0
flags:
  svod:
    library-only: false
    dev: false
