resolver: nightly-2015-12-27
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: eff6991902badfd14e4a418433d3e8cbc334884a
flags:
  svod:
    library-only: false
    dev: false
