resolver: nightly-2015-12-02
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 90bab9904d6781b8903470d8214028f0b4841dfb
flags:
  svod:
    library-only: false
    dev: false
