resolver: nightly-2016-03-13
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: f6006bb769173acfc853d08c62848c56a670e0b7
flags:
  svod:
    library-only: false
    dev: false
