resolver: nightly-2015-12-27
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: ccbb24c10810be10eff0aa3cf144a54a13dbcd7a
flags:
  svod:
    library-only: false
    dev: false
