resolver: nightly-2016-03-13
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 95ceba943b80f3683026a2c095f9725a611081b3
flags:
  svod:
    library-only: false
    dev: false
