resolver: nightly-2016-03-13
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 4856c51c9ba3ee8fe636c0a9ebb7adc5c6a70257
flags:
  svod:
    library-only: false
    dev: false
