resolver: nightly-2016-03-13
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 8a704c75c1ac755fbd3c8fe611b6633973432dac
flags:
  svod:
    library-only: false
    dev: false
