resolver: nightly-2015-12-02
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: cdb08a0db8e4980b6aadfa320293070f24481baa
flags:
  svod:
    library-only: false
    dev: false
